[package]
name = "dotty"
version = "0.0.0"
authors = ["Keith Hendry <keithahendry@gmail.com>"]
description = "Dotfiles using symlinks and git"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.7", features = ["derive", "env"] }
git2 = "0.15.0"
home-dir = "0.1.0"
libgit2-sys = "0.14.0"
log = "0.4.14"
openssl = { version = "0.10.42", features = ["vendored"] }
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.9.13"
simplelog = { version = "0.12.0", features = ["paris"] }
