name: Label PR's

on:
  pull_request_target:
    types: [ opened, edited ]

jobs:
  label:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: {
            "feat": "feature",
            "fix": "fix",
            "breaking": "breaking",
            "docs": "documentation",
            "style": "style",
            "refactor": "refactored",
            "test": "testing",
          }
