name: Label PR's

on:
  pull_request_target:
    types: [ opened, edited ]

jobs:
  label:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: |
            {
              "feat": "feature",
              "fix": "fix",
              "breaking": "breaking",
              "docs": "documentation",
              "perf": "performance",
              "revert": "revert",
              "style": "style",
              "refactor": "refactor",
              "test": "testing",
              "chore": "chore",
            }
          ignored_types: |
            [
              "style",
              "refactor",
              "test",
              "chore"
            ]
