name: Release Builds

on:
  push:
    tags:        
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-darwin-arm64:
    name: Build MacOS arm64
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set version
      id: vars
      run: |
        TAG=${GITHUB_REF#refs/*/}
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        sed -i .bak "s/0.0.0/$TAG/g" Cargo.toml
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -Z unstable-options --target aarch64-apple-darwin --release
    - name: Copy
      run: |
        mkdir -p out/
        cp target/aarch64-apple-darwin/release/dotty out/dotty-${{ steps.vars.outputs.tag }}-darwin-arm64
    - name: Upload
      uses: actions/upload-artifact@v3
      with: 
        name: build-darwin-arm64
        path: out/dotty-${{ steps.vars.outputs.tag }}-darwin-arm64

  build-darwin-x86_64:
    name: Build MacOS x86-64
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set version
      id: vars
      run: |
        TAG=${GITHUB_REF#refs/*/}
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        sed -i .bak "s/0.0.0/$TAG/g" Cargo.toml
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -Z unstable-options --target x86_64-apple-darwin --release
    - name: Copy
      run: |
        mkdir -p out/
        cp target/x86_64-apple-darwin/release/dotty out/dotty-${{ steps.vars.outputs.tag }}-darwin-x86_64
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: build-darwin-x86_64
        path: out/dotty-${{ steps.vars.outputs.tag }}-darwin-x86_64

  release:
    name: Create Release
    needs:
      - build-darwin-arm64
      - build-darwin-x86_64
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
          build-darwin-arm64/*
          build-darwin-x86_64/*
