name: Release Builds

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-darwin-arm64:
    name: Build MacOS arm64
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set version
        run: |
          sed -i .bak "s/0.0.0/$GITHUB_REF_NAME/g" Cargo.toml
      - name: Setup Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup show
      - name: Build
        run: |
          cargo build -Z unstable-options --target aarch64-apple-darwin --release
      - name: Tar
        run: |
          cd target/aarch64-apple-darwin/release
          tar -czvf dotty-${{ github.ref_name }}-darwin-arm64.tar.gz dotty
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-darwin-arm64
          path: target/aarch64-apple-darwin/release/dotty-${{ github.ref_name }}-darwin-arm64.tar.gz

  build-darwin-amd64:
    name: Build MacOS amd64
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set version
        run: |
          sed -i .bak "s/0.0.0/$GITHUB_REF_NAME/g" Cargo.toml
      - name: Setup Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup show
      - name: Build
        run: |
          cargo build -Z unstable-options --target x86_64-apple-darwin --release
      - name: Tar
        run: |
          cd target/x86_64-apple-darwin/release
          tar -czvf dotty-${{ github.ref_name  }}-darwin-amd64.tar.gz dotty
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-darwin-amd64
          path: target/x86_64-apple-darwin/release/dotty-${{ github.ref_name }}-darwin-amd64.tar.gz

  build-linux-amd64:
    name: Build Linux amd64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set version
        run: |
          sed -i "s/0.0.0/$GITHUB_REF_NAME/g" Cargo.toml
      - name: Setup Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup show
      - name: Build
        run: |
          cargo build -Z unstable-options --target x86_64-unknown-linux-gnu --release
      - name: Tar
        run: |
          cd target/x86_64-unknown-linux-gnu/release
          tar -czvf dotty-${{ github.ref_name  }}-linux-amd64.tar.gz dotty
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-linux-amd64
          path: target/x86_64-unknown-linux-gnu/release/dotty-${{ github.ref_name  }}-linux-amd64.tar.gz

  release:
    name: Create Release
    needs:
      - build-darwin-arm64
      - build-darwin-amd64
      - build-linux-amd64
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            build-darwin-arm64/*
            build-darwin-amd64/*
            build-linux-amd64/*

  homebrew-releaser:
    name: Homebrew Releaser
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.HOMEBREW_DOTTY_PR_APP_ID }}
          private_key: ${{ secrets.HOMEBREW_DOTTY_PR_APP_PRIVATE_KEY }}
          repository: keithhendry/homebrew-dotty
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: keithhendry/homebrew-dotty
          token: ${{ steps.generate-token.outputs.token }}
      - name: Generate
        run: |
          src/generate.py \
            --platform darwin/amd64 \
            --platform darwin/arm64 \
            --platform linux/amd64 \
            --version ${{ github.ref_name }}
      - name: Push Release
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git config push.default current

          git checkout -b "release/${{ github.ref_name }}"
          git add -A
          git commit -m "release: ${{ github.ref_name }}"

          git push
      - name: Create PR
        run: |
          pr_url="$(gh pr create --fill)"
          gh pr merge --auto --squash "$pr_url"
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
