name: Release Builds

on:
  push:
    tags:        
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-darwin-arm64:
    name: Build MacOS arm64
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set version
      run: |
        sed -i .bak "s/0.0.0/$GITHUB_REF_NAME/g" Cargo.toml
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -Z unstable-options --target aarch64-apple-darwin --release
    - name: Tar
      run: |
        cd target/aarch64-apple-darwin/release
        tar -czvf dotty-${{ github.ref_name }}-darwin-arm64.tar.gz dotty
    - name: Upload
      uses: actions/upload-artifact@v3
      with: 
        name: build-darwin-arm64
        path: target/aarch64-apple-darwin/release/dotty-${{ github.ref_name }}-darwin-arm64.tar.gz

  build-darwin-amd64:
    name: Build MacOS amd64
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set version
      run: |
        sed -i .bak "s/0.0.0/$GITHUB_REF_NAME/g" Cargo.toml
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -Z unstable-options --target x86_64-apple-darwin --release
    - name: Tar
      run: |
        cd target/x86_64-apple-darwin/release
        tar -czvf dotty-${{ github.ref_name  }}-darwin-amd64.tar.gz dotty
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: build-darwin-amd64
        path: target/x86_64-apple-darwin/release/dotty-${{ github.ref_name }}-darwin-amd64.tar.gz

  collect-artifacts:
    name: Collect Artifacts
    needs:
      - build-darwin-arm64
      - build-darwin-amd64
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Consolidate release artifacts
      run: |
        mkdir -p artifacts/
        cp build-darwin-arm64/* build-darwin-amd64/* artifacts/
    - name: Calculate checksums
      run: |
        cd artifacts
        shasum -a 256 * > checksum.txt
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: collect-artifacts
        path: artifacts/

  release:
    name: Create Release
    needs: collect-artifacts
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: collect-artifacts
        path: collect-artifacts
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
          collect-artifacts/*

  homebrew-releaser:
    name: Homebrew Releaser
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: collect-artifacts
          path: collect-artifacts
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: homebrew-dotty
          ssh-key: "${{ secrets.HOMEBREW_RELEASE_KEY }}"
      - name: Generate formula
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git config push.default current

          mkdir -p formula
          src/generate.py \
            --checksums-path collect-artifacts/checksum.txt \
            --platform darwin/amd64 \
            --platform darwin/arm64 \
            --version ${{ github.ref_name }} > formula/dotty.rb

          git add formula/dotty.rb
          git commit -m "Brew formula update for dotty version ${{ github.ref_name }}"
          git push
