name: Release Builds

on:
  push:
    tags:        
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-darwin-arm64:
    name: Build MacOS arm64
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set version
      id: vars
      run: |
        TAG=${GITHUB_REF#refs/*/}
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        sed -i .bak "s/0.0.0/$TAG/g" Cargo.toml
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -Z unstable-options --target aarch64-apple-darwin --release
    - name: Tar
      run: |
        cd target/aarch64-apple-darwin/release
        tar -czvf dotty-${{ steps.vars.outputs.tag }}-darwin-arm64.tar.gz dotty
    - name: Upload
      uses: actions/upload-artifact@v3
      with: 
        name: build-darwin-arm64
        path: target/aarch64-apple-darwin/release/dotty-${{ steps.vars.outputs.tag }}-darwin-arm64.tar.gz

  build-darwin-amd64:
    name: Build MacOS amd64
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set version
      id: vars
      run: |
        TAG=${GITHUB_REF#refs/*/}
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        sed -i .bak "s/0.0.0/$TAG/g" Cargo.toml
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -Z unstable-options --target x86_64-apple-darwin --release
    - name: Tar
      run: |
        cd target/x86_64-apple-darwin/release
        tar -czvf dotty-${{ steps.vars.outputs.tag }}-darwin-amd64.tar.gz dotty
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: build-darwin-amd64
        path: target/x86_64-apple-darwin/release/dotty-${{ steps.vars.outputs.tag }}-darwin-amd64.tar.gz

  release:
    name: Create Release
    needs:
      - build-darwin-arm64
      - build-darwin-amd64
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
          build-darwin-arm64/*
          build-darwin-amd64/*

  homebrew-releaser:
    name: Homebrew Releaser
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Release my project to my Homebrew tap
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: keithhendry
          homebrew_tap: homebrew-dotty
          commit_owner: GitHub Actions Bot
          commit_email: <>
          formula_folder: formula
          github_token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          install: 'bin.install "dotty"'
          test: 'system "#{bin}/dotty", "--version"'
          target_darwin_amd64: true
          target_darwin_arm64: true
          update_readme_table: true
